// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/src/main/proto/hello_world.proto

package io.grpc.examples.helloworld;

public interface ChannelLastMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.ChannelLastMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string channel = 1;</code>
   */
  java.lang.String getChannel();
  /**
   * <code>optional string channel = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelBytes();

  /**
   * <code>optional int32 lastId = 2;</code>
   */
  int getLastId();
}
