// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/src/main/proto/hello_world.proto

package io.grpc.examples.helloworld;

/**
 * Protobuf type {@code helloworld.MessageRequest}
 */
public  final class MessageRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helloworld.MessageRequest)
    MessageRequestOrBuilder {
  // Use MessageRequest.newBuilder() to construct.
  private MessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MessageRequest() {
    clm_ = java.util.Collections.emptyList();
    token_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              clm_ = new java.util.ArrayList<io.grpc.examples.helloworld.ChannelLastMsg>();
              mutable_bitField0_ |= 0x00000001;
            }
            clm_.add(input.readMessage(io.grpc.examples.helloworld.ChannelLastMsg.parser(), extensionRegistry));
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        clm_ = java.util.Collections.unmodifiableList(clm_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.examples.helloworld.HelloWorldProto.internal_static_helloworld_MessageRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.examples.helloworld.HelloWorldProto.internal_static_helloworld_MessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.examples.helloworld.MessageRequest.class, io.grpc.examples.helloworld.MessageRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CLM_FIELD_NUMBER = 1;
  private java.util.List<io.grpc.examples.helloworld.ChannelLastMsg> clm_;
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  public java.util.List<io.grpc.examples.helloworld.ChannelLastMsg> getClmList() {
    return clm_;
  }
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  public java.util.List<? extends io.grpc.examples.helloworld.ChannelLastMsgOrBuilder> 
      getClmOrBuilderList() {
    return clm_;
  }
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  public int getClmCount() {
    return clm_.size();
  }
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  public io.grpc.examples.helloworld.ChannelLastMsg getClm(int index) {
    return clm_.get(index);
  }
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  public io.grpc.examples.helloworld.ChannelLastMsgOrBuilder getClmOrBuilder(
      int index) {
    return clm_.get(index);
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object token_;
  /**
   * <code>optional string token = 2;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>optional string token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < clm_.size(); i++) {
      output.writeMessage(1, clm_.get(i));
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, token_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < clm_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, clm_.get(i));
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, token_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static io.grpc.examples.helloworld.MessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.examples.helloworld.MessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.MessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.MessageRequest)
      io.grpc.examples.helloworld.MessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.helloworld.HelloWorldProto.internal_static_helloworld_MessageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.helloworld.HelloWorldProto.internal_static_helloworld_MessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.helloworld.MessageRequest.class, io.grpc.examples.helloworld.MessageRequest.Builder.class);
    }

    // Construct using io.grpc.examples.helloworld.MessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getClmFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (clmBuilder_ == null) {
        clm_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        clmBuilder_.clear();
      }
      token_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.examples.helloworld.HelloWorldProto.internal_static_helloworld_MessageRequest_descriptor;
    }

    public io.grpc.examples.helloworld.MessageRequest getDefaultInstanceForType() {
      return io.grpc.examples.helloworld.MessageRequest.getDefaultInstance();
    }

    public io.grpc.examples.helloworld.MessageRequest build() {
      io.grpc.examples.helloworld.MessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.examples.helloworld.MessageRequest buildPartial() {
      io.grpc.examples.helloworld.MessageRequest result = new io.grpc.examples.helloworld.MessageRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (clmBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          clm_ = java.util.Collections.unmodifiableList(clm_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.clm_ = clm_;
      } else {
        result.clm_ = clmBuilder_.build();
      }
      result.token_ = token_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.examples.helloworld.MessageRequest) {
        return mergeFrom((io.grpc.examples.helloworld.MessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.examples.helloworld.MessageRequest other) {
      if (other == io.grpc.examples.helloworld.MessageRequest.getDefaultInstance()) return this;
      if (clmBuilder_ == null) {
        if (!other.clm_.isEmpty()) {
          if (clm_.isEmpty()) {
            clm_ = other.clm_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureClmIsMutable();
            clm_.addAll(other.clm_);
          }
          onChanged();
        }
      } else {
        if (!other.clm_.isEmpty()) {
          if (clmBuilder_.isEmpty()) {
            clmBuilder_.dispose();
            clmBuilder_ = null;
            clm_ = other.clm_;
            bitField0_ = (bitField0_ & ~0x00000001);
            clmBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getClmFieldBuilder() : null;
          } else {
            clmBuilder_.addAllMessages(other.clm_);
          }
        }
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.examples.helloworld.MessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.examples.helloworld.MessageRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.grpc.examples.helloworld.ChannelLastMsg> clm_ =
      java.util.Collections.emptyList();
    private void ensureClmIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        clm_ = new java.util.ArrayList<io.grpc.examples.helloworld.ChannelLastMsg>(clm_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.grpc.examples.helloworld.ChannelLastMsg, io.grpc.examples.helloworld.ChannelLastMsg.Builder, io.grpc.examples.helloworld.ChannelLastMsgOrBuilder> clmBuilder_;

    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public java.util.List<io.grpc.examples.helloworld.ChannelLastMsg> getClmList() {
      if (clmBuilder_ == null) {
        return java.util.Collections.unmodifiableList(clm_);
      } else {
        return clmBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public int getClmCount() {
      if (clmBuilder_ == null) {
        return clm_.size();
      } else {
        return clmBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public io.grpc.examples.helloworld.ChannelLastMsg getClm(int index) {
      if (clmBuilder_ == null) {
        return clm_.get(index);
      } else {
        return clmBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder setClm(
        int index, io.grpc.examples.helloworld.ChannelLastMsg value) {
      if (clmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClmIsMutable();
        clm_.set(index, value);
        onChanged();
      } else {
        clmBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder setClm(
        int index, io.grpc.examples.helloworld.ChannelLastMsg.Builder builderForValue) {
      if (clmBuilder_ == null) {
        ensureClmIsMutable();
        clm_.set(index, builderForValue.build());
        onChanged();
      } else {
        clmBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder addClm(io.grpc.examples.helloworld.ChannelLastMsg value) {
      if (clmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClmIsMutable();
        clm_.add(value);
        onChanged();
      } else {
        clmBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder addClm(
        int index, io.grpc.examples.helloworld.ChannelLastMsg value) {
      if (clmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClmIsMutable();
        clm_.add(index, value);
        onChanged();
      } else {
        clmBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder addClm(
        io.grpc.examples.helloworld.ChannelLastMsg.Builder builderForValue) {
      if (clmBuilder_ == null) {
        ensureClmIsMutable();
        clm_.add(builderForValue.build());
        onChanged();
      } else {
        clmBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder addClm(
        int index, io.grpc.examples.helloworld.ChannelLastMsg.Builder builderForValue) {
      if (clmBuilder_ == null) {
        ensureClmIsMutable();
        clm_.add(index, builderForValue.build());
        onChanged();
      } else {
        clmBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder addAllClm(
        java.lang.Iterable<? extends io.grpc.examples.helloworld.ChannelLastMsg> values) {
      if (clmBuilder_ == null) {
        ensureClmIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, clm_);
        onChanged();
      } else {
        clmBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder clearClm() {
      if (clmBuilder_ == null) {
        clm_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        clmBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public Builder removeClm(int index) {
      if (clmBuilder_ == null) {
        ensureClmIsMutable();
        clm_.remove(index);
        onChanged();
      } else {
        clmBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public io.grpc.examples.helloworld.ChannelLastMsg.Builder getClmBuilder(
        int index) {
      return getClmFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public io.grpc.examples.helloworld.ChannelLastMsgOrBuilder getClmOrBuilder(
        int index) {
      if (clmBuilder_ == null) {
        return clm_.get(index);  } else {
        return clmBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public java.util.List<? extends io.grpc.examples.helloworld.ChannelLastMsgOrBuilder> 
         getClmOrBuilderList() {
      if (clmBuilder_ != null) {
        return clmBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(clm_);
      }
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public io.grpc.examples.helloworld.ChannelLastMsg.Builder addClmBuilder() {
      return getClmFieldBuilder().addBuilder(
          io.grpc.examples.helloworld.ChannelLastMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public io.grpc.examples.helloworld.ChannelLastMsg.Builder addClmBuilder(
        int index) {
      return getClmFieldBuilder().addBuilder(
          index, io.grpc.examples.helloworld.ChannelLastMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
     */
    public java.util.List<io.grpc.examples.helloworld.ChannelLastMsg.Builder> 
         getClmBuilderList() {
      return getClmFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.grpc.examples.helloworld.ChannelLastMsg, io.grpc.examples.helloworld.ChannelLastMsg.Builder, io.grpc.examples.helloworld.ChannelLastMsgOrBuilder> 
        getClmFieldBuilder() {
      if (clmBuilder_ == null) {
        clmBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.grpc.examples.helloworld.ChannelLastMsg, io.grpc.examples.helloworld.ChannelLastMsg.Builder, io.grpc.examples.helloworld.ChannelLastMsgOrBuilder>(
                clm_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        clm_ = null;
      }
      return clmBuilder_;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:helloworld.MessageRequest)
  }

  // @@protoc_insertion_point(class_scope:helloworld.MessageRequest)
  private static final io.grpc.examples.helloworld.MessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.examples.helloworld.MessageRequest();
  }

  public static io.grpc.examples.helloworld.MessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<MessageRequest>() {
    public MessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new MessageRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<MessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageRequest> getParserForType() {
    return PARSER;
  }

  public io.grpc.examples.helloworld.MessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

