// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/src/main/proto/hello_world.proto

package io.grpc.examples.helloworld;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  java.util.List<io.grpc.examples.helloworld.ChannelLastMsg> 
      getClmList();
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  io.grpc.examples.helloworld.ChannelLastMsg getClm(int index);
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  int getClmCount();
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  java.util.List<? extends io.grpc.examples.helloworld.ChannelLastMsgOrBuilder> 
      getClmOrBuilderList();
  /**
   * <code>repeated .helloworld.ChannelLastMsg clm = 1;</code>
   */
  io.grpc.examples.helloworld.ChannelLastMsgOrBuilder getClmOrBuilder(
      int index);

  /**
   * <code>optional string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
